# Generated by Django 3.1.7 on 2021-04-14 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plots', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='properties',
            name='Img',
        ),
    ]
