# Generated by Django 3.1.7 on 2021-04-14 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plots', '0002_remove_properties_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='Img',
            field=models.ImageField(default=None, upload_to='images/'),
        ),
    ]
