# Generated by Django 3.1.7 on 2021-04-14 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plots', '0003_properties_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='title_slug',
            field=models.SlugField(default=models.CharField(default='No Title property', max_length=500), max_length=255),
        ),
    ]
