# Generated by Django 3.1.7 on 2021-04-14 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plots', '0004_auto_20210414_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='title_slug',
            field=models.SlugField(default='', editable=False, max_length=255),
        ),
    ]
