# Generated by Django 3.1.7 on 2021-04-14 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plots', '0005_auto_20210414_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='title_slug',
            field=models.SlugField(max_length=255),
        ),
    ]
