# Generated by Django 3.1.7 on 2021-04-15 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import plots.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plots', '0006_auto_20210414_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='name',
            name='email',
            field=models.EmailField(default='abc@gmail.com', max_length=100, validators=[plots.models.check_gmail]),
        ),
        migrations.AddField(
            model_name='name',
            name='password1',
            field=models.CharField(default='******', max_length=14),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('location', models.CharField(blank=True, max_length=30)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
