# Generated by Django 3.1.7 on 2021-04-18 17:34

from django.db import migrations, models
import django.db.models.deletion
import plots.models


class Migration(migrations.Migration):

    dependencies = [
        ('plots', '0007_auto_20210415_2335'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Name',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='name',
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='abc@gmail.com', max_length=100, validators=[plots.models.check_gmail]),
        ),
        migrations.AddField(
            model_name='profile',
            name='password1',
            field=models.CharField(default='******', max_length=14),
        ),
        migrations.AlterField(
            model_name='properties',
            name='Name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='property', to='plots.profile'),
        ),
    ]
