# Generated by Django 3.1.7 on 2021-04-18 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plots', '0008_auto_20210418_2304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='properties',
            name='Name',
        ),
    ]
