# Generated by Django 3.1.7 on 2021-04-30 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plots', '0009_remove_properties_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='properties',
            old_name='title_slug',
            new_name='slug',
        ),
    ]
